### ISSUE TITLE
"8 queens" crashes metaphone

### ISSUE THREAD

**Issue by paultag** [jamesturk/go-jellyfish#3]
Sorry for the flood of reports :)

```
(dictd)(ocd)[tag@cassiel:~/dev/local/go-jellyfish][⎇  master] ♥  cat ~/main.go 
package main

import (
	"fmt"
	"github.com/jamesturk/go-jellyfish"
)

func main() {
	fmt.Printf("%s\n", jellyfish.Metaphone("8 queens"))
}
(dictd)(ocd)[tag@cassiel:~/dev/local/go-jellyfish][⎇  master] ♥  go run ~/main.go 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jamesturk/go-jellyfish.Metaphone(0x505090, 0x8, 0x0, 0x0)
	/home/tag/.goenvs/dictd/src/github.com/jamesturk/go-jellyfish/metaphone.go:154 +0x355
main.main()
	/home/tag/main.go:9 +0x3c

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/lib/go/src/runtime/proc.go:90
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/lib/go/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/lib/go/src/runtime/malloc.go:712
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
(dictd)(ocd)[tag@cassiel:~/dev/local/go-jellyfish][⎇  master] ♥  
```

**Comment by paultag** [comment]
I think this solves it

```diff
diff --git a/metaphone.go b/metaphone.go
index e7d772d..3614090 100644
--- a/metaphone.go
+++ b/metaphone.go
@@ -151,7 +151,7 @@ func Metaphone(s string) string {
                case 'Z':
                        result = append(result, 'S')
                case ' ':
-                       if result[len(result)-1] != ' ' {
+                       if len(result) > 0 && result[len(result)-1] != ' ' {
                                result = append(result, ' ')
                        }
                }
```

**Comment by jamesturk** [comment]
thanks!  keep 'em coming, this one def. affected the C/Py ones

**Comment by paultag** [comment]
:+1:, thanks!
